// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/chat.dart';
import 'api/rooms.dart';
import 'api/session.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<List<ChatMessage>> dco_decode_StreamSink_list_chat_message_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<RoomSummary>> dco_decode_StreamSink_list_room_summary_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SyncStatus> dco_decode_StreamSink_sync_status_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthError dco_decode_auth_error(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SessionData dco_decode_box_autoadd_session_data(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ChatError dco_decode_chat_error(dynamic raw);

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw);

  @protected
  DeliveryState dco_decode_delivery_state(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RoomSummary> dco_decode_list_room_summary(dynamic raw);

  @protected
  MessageKind dco_decode_message_kind(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  RoomSummary dco_decode_room_summary(dynamic raw);

  @protected
  SessionData dco_decode_session_data(dynamic raw);

  @protected
  SyncError dco_decode_sync_error(dynamic raw);

  @protected
  SyncStatus dco_decode_sync_status(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<List<ChatMessage>> sse_decode_StreamSink_list_chat_message_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<RoomSummary>> sse_decode_StreamSink_list_room_summary_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncStatus> sse_decode_StreamSink_sync_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthError sse_decode_auth_error(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SessionData sse_decode_box_autoadd_session_data(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ChatError sse_decode_chat_error(SseDeserializer deserializer);

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer);

  @protected
  DeliveryState sse_decode_delivery_state(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RoomSummary> sse_decode_list_room_summary(SseDeserializer deserializer);

  @protected
  MessageKind sse_decode_message_kind(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  RoomSummary sse_decode_room_summary(SseDeserializer deserializer);

  @protected
  SessionData sse_decode_session_data(SseDeserializer deserializer);

  @protected
  SyncError sse_decode_sync_error(SseDeserializer deserializer);

  @protected
  SyncStatus sse_decode_sync_status(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_chat_message_Sse(
    RustStreamSink<List<ChatMessage>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_room_summary_Sse(
    RustStreamSink<List<RoomSummary>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_status_Sse(
    RustStreamSink<SyncStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_error(AuthError self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_session_data(
    SessionData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_chat_error(ChatError self, SseSerializer serializer);

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer);

  @protected
  void sse_encode_delivery_state(DeliveryState self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_chat_message(
    List<ChatMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_room_summary(
    List<RoomSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_kind(MessageKind self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_room_summary(RoomSummary self, SseSerializer serializer);

  @protected
  void sse_encode_session_data(SessionData self, SseSerializer serializer);

  @protected
  void sse_encode_sync_error(SyncError self, SseSerializer serializer);

  @protected
  void sse_encode_sync_status(SyncStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
