// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `delivery_of`, `describe`, `publish`, `sender_name`, `to_message`, `undecryptable_kind`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `watch_messages_with`

Future<void> openRoom({required String roomId}) =>
    RustLib.instance.api.crateApiChatOpenRoom(roomId: roomId);

Future<void> closeRoom({required String roomId}) =>
    RustLib.instance.api.crateApiChatCloseRoom(roomId: roomId);

Future<void> sendMessage({required String roomId, required String text}) =>
    RustLib.instance.api.crateApiChatSendMessage(roomId: roomId, text: text);

Future<void> retrySend({required String roomId, required String messageId}) =>
    RustLib.instance.api.crateApiChatRetrySend(
      roomId: roomId,
      messageId: messageId,
    );

Future<bool> loadOlderMessages({required String roomId, required int count}) =>
    RustLib.instance.api.crateApiChatLoadOlderMessages(
      roomId: roomId,
      count: count,
    );

Stream<List<ChatMessage>> watchMessages({required String roomId}) =>
    RustLib.instance.api.crateApiChatWatchMessages(roomId: roomId);

enum ChatError {
  notLoggedIn,
  roomNotFound,
  messageNotFound,
  failed,
}

class ChatMessage {
  final String id;
  final String senderId;
  final String senderName;
  final String text;
  final BigInt sentAtMs;
  final bool isOwn;
  final MessageKind kind;
  final DeliveryState delivery;

  const ChatMessage({
    required this.id,
    required this.senderId,
    required this.senderName,
    required this.text,
    required this.sentAtMs,
    required this.isOwn,
    required this.kind,
    required this.delivery,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderId.hashCode ^
      senderName.hashCode ^
      text.hashCode ^
      sentAtMs.hashCode ^
      isOwn.hashCode ^
      kind.hashCode ^
      delivery.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          text == other.text &&
          sentAtMs == other.sentAtMs &&
          isOwn == other.isOwn &&
          kind == other.kind &&
          delivery == other.delivery;
}

enum DeliveryState {
  sending,
  sent,
  failed,
}

enum MessageKind {
  text,
  encrypted,
  encryptedKeysNeeded,
  encryptedUnavailable,
  other,
}
