// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `invited_room`, `to_invite`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `watch_invites_with`

Future<String> createConversation({required String userId}) => RustLib
    .instance
    .api
    .crateApiConversationsCreateConversation(userId: userId);

Future<void> acceptInvite({required String roomId}) =>
    RustLib.instance.api.crateApiConversationsAcceptInvite(roomId: roomId);

Future<void> declineInvite({required String roomId}) =>
    RustLib.instance.api.crateApiConversationsDeclineInvite(roomId: roomId);

Stream<List<InviteSummary>> watchInvites() =>
    RustLib.instance.api.crateApiConversationsWatchInvites();

enum ConversationError {
  notLoggedIn,
  invalidUser,
  selfConversation,
  userNotFound,
  roomNotFound,
  failed,
}

class InviteSummary {
  final String roomId;
  final String name;
  final String inviterId;
  final String inviterName;

  const InviteSummary({
    required this.roomId,
    required this.name,
    required this.inviterId,
    required this.inviterName,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      name.hashCode ^
      inviterId.hashCode ^
      inviterName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteSummary &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          name == other.name &&
          inviterId == other.inviterId &&
          inviterName == other.inviterName;
}
