// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_recovery_error`, `map_state`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `watch_recovery_status_with`

Stream<RecoveryStatus> watchRecoveryStatus() =>
    RustLib.instance.api.crateApiEncryptionWatchRecoveryStatus();

Future<void> recoverKeys({required String recoveryKey}) => RustLib.instance.api
    .crateApiEncryptionRecoverKeys(recoveryKey: recoveryKey);

Future<String> enableRecovery() =>
    RustLib.instance.api.crateApiEncryptionEnableRecovery();

enum EncryptionError {
  notLoggedIn,
  invalidKey,
  backupExists,
  network,
  failed,
}

enum RecoveryStatus {
  unknown,
  enabled,
  disabled,
  incomplete,
}
