// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_unknown_token`, `last_message_text`, `map_state`, `resolve_status`, `to_summary`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `watch_rooms_with`, `watch_sync_status_with`

Future<void> startSync() => RustLib.instance.api.crateApiRoomsStartSync();

Future<void> stopSync() => RustLib.instance.api.crateApiRoomsStopSync();

Stream<SyncStatus> watchSyncStatus() =>
    RustLib.instance.api.crateApiRoomsWatchSyncStatus();

Stream<List<RoomSummary>> watchRooms() =>
    RustLib.instance.api.crateApiRoomsWatchRooms();

class RoomSummary {
  final String id;
  final String name;
  final String? lastMessage;
  final BigInt? lastMessageAtMs;
  final BigInt unreadCount;
  final BigInt memberCount;

  const RoomSummary({
    required this.id,
    required this.name,
    this.lastMessage,
    this.lastMessageAtMs,
    required this.unreadCount,
    required this.memberCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      lastMessage.hashCode ^
      lastMessageAtMs.hashCode ^
      unreadCount.hashCode ^
      memberCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          lastMessage == other.lastMessage &&
          lastMessageAtMs == other.lastMessageAtMs &&
          unreadCount == other.unreadCount &&
          memberCount == other.memberCount;
}

enum SyncError {
  notLoggedIn,
  sessionExpired,
  failed,
}

enum SyncStatus {
  idle,
  running,
  offline,
  sessionExpired,
  failed,
  stopped,
}
