// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_client`, `map_build_error`, `map_error_kind`, `to_session_data`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`

Future<SessionData> login({
  required String homeserverUrl,
  required String username,
  required String password,
  required String dataDir,
  required String passphrase,
}) => RustLib.instance.api.crateApiSessionLogin(
  homeserverUrl: homeserverUrl,
  username: username,
  password: password,
  dataDir: dataDir,
  passphrase: passphrase,
);

Future<void> restoreSession({
  required SessionData session,
  required String dataDir,
  required String passphrase,
}) => RustLib.instance.api.crateApiSessionRestoreSession(
  session: session,
  dataDir: dataDir,
  passphrase: passphrase,
);

Future<void> logout() => RustLib.instance.api.crateApiSessionLogout();

enum AuthError {
  invalidHomeserver,
  network,
  invalidCredentials,
  rateLimited,
  sessionExpired,
  storage,
  notLoggedIn,
  unknown,
}

class SessionData {
  final String homeserverUrl;
  final String userId;
  final String deviceId;
  final String accessToken;
  final String? refreshToken;

  const SessionData({
    required this.homeserverUrl,
    required this.userId,
    required this.deviceId,
    required this.accessToken,
    this.refreshToken,
  });

  @override
  int get hashCode =>
      homeserverUrl.hashCode ^
      userId.hashCode ^
      deviceId.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionData &&
          runtimeType == other.runtimeType &&
          homeserverUrl == other.homeserverUrl &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken;
}
